version: oggz-travis-{build}
image: Visual Studio 2017
configuration: Debug
platform:
  - Win32
  - x64
install:
  - choco install doxygen.install
  - cd ..
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg integrate install
  - if %platform%==Win32 set VCPKG_TRIPLET=x86-windows
  - if %platform%==x64 set VCPKG_TRIPLET=x64-windows
  - vcpkg install libogg:%VCPKG_TRIPLET%
  - cd ..\oggz
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake
build:
  project: c:\projects\oggz\CMakeBuild\oggz.sln
  verbosity: minimal
test_script:
  - ctest -V
